extends: site.yaml
mode: production
base_url: /dikteeri
media_url: /dikteeri/media

publisher:
        ssh:
            type: hyde.ext.publishers.ssh.SSH
            username: webspeech
            server: fourier
            target: /var/www/dikteeri
            command: rsync
            opts: -r -e ssh
