mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
base_url : http://localhost:8080
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - local.i18NPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.tagger.TaggerPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        site_title: Dikteerimine
        author:
            name: TTÜ Küberneetika Instituudi foneetika ja kõnetehnoloogia labor
            url: "http://www.phon.ioc.ee"
        google_analytics_id: UA-18651078-4
        home_url: index.html
        menu:
            - title: Tutvustus
              url: about.html

i18N:
    locales:
        - en
        - et

meta:
    lc: et
    encoding: 'utf-8'
    nodemeta: meta.yaml
    created: !!timestamp 2010-01-01 00:00:00
    author: Tanel Alumäe
